// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKp2ZqowSRd4lDREl3q2xxinAmP7p6Bm0',
    appId: '1:915926007082:web:9c4f43cc29946c2520b253',
    messagingSenderId: '915926007082',
    projectId: 'chat-app-a3657',
    authDomain: 'chat-app-a3657.firebaseapp.com',
    storageBucket: 'chat-app-a3657.appspot.com',
    measurementId: 'G-DEVH95WDKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1M4g0sb7qUqiWsb-Wh0UKZlS2YM430YQ',
    appId: '1:915926007082:android:9e5a4443c85e870520b253',
    messagingSenderId: '915926007082',
    projectId: 'chat-app-a3657',
    storageBucket: 'chat-app-a3657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYuTfAPgaQMBK7ve_kJ-hF6jLUelJqVE',
    appId: '1:915926007082:ios:d6ce3f8315fb7f5320b253',
    messagingSenderId: '915926007082',
    projectId: 'chat-app-a3657',
    storageBucket: 'chat-app-a3657.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
